tap "getantibody/tap"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "asdf"
brew "awscli"
brew "bash"
brew "blueutil"
brew "coreutils"
brew "ctags"
brew "curl"
brew "direnv"
brew "docker"
brew "ffmpeg"
brew "getantibody/tap/antibody"
brew "git"
brew "gnupg"
brew "grep"
brew "highlight"
brew "htop"
brew "hub"
cask "hyper"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "markdown"
brew "mas"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "postgresql"
brew "ripgrep"
brew "ruby-build"
brew "redis", restart_service: true
brew "sed"
brew "shellcheck"
brew "terraform"
brew "terraform-docs"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "z"
brew "zsh"

cask "alfred"
cask "calibre"
cask "dropbox"
cask "evernote"
cask "flux"
cask "font-consolas-for-powerline"
cask "font-fira-code"
cask "font-inconsolata"
cask "font-inconsolata-for-powerline"
cask "font-roboto-mono"
cask "font-roboto-mono-for-powerline"
cask "google-chrome"
cask "karabiner"
cask "postman"
cask "sequel-pro"
cask "skype"
cask "spectacle"
cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vlc"
cask "windscribe"
cask "zoomus"

mas '1password 7', id: 1333542190
mas 'Evernote', id: 406056744
mas 'Clocky', id: 414554506
mas 'GarageBand', 682658836
