# code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension 4ops.terraform
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.path-intellisense
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension eryouhao.brackets-light-pro
code --install-extension felipe-mendes.slack-theme
code --install-extension justusadam.language-haskell
code --install-extension KnisterPeter.vscode-github
code --install-extension lukasz-wronski.ftp-sync
code --install-extension mariorodeghiero.vue-theme
code --install-extension mjmcloug.vscode-elixir
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.mssql
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension redhat.vscode-yaml
code --install-extension Shan.code-settings-sync
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shengchen.vscode-leetcode
code --install-extension teabyii.ayu
code --install-extension tinkertrain.theme-panda
