# code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension 4ops.terraform
code --install-extension andyyaldoo.vscode-json
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.path-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension eryouhao.brackets-light-pro
code --install-extension esbenp.prettier-vscode
code --install-extension felipe-mendes.slack-theme
code --install-extension FerrierBenjamin.fold-unfold-all-icone
code --install-extension jgodi.vscode-touchbar-powerpack
code --install-extension justusadam.language-haskell
code --install-extension KnisterPeter.vscode-github
code --install-extension lukasz-wronski.ftp-sync
code --install-extension mariorodeghiero.vue-theme
code --install-extension mjmcloug.vscode-elixir
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-mssql.mssql
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension redhat.vscode-yaml
code --install-extension Shan.code-settings-sync
code --install-extension shardulm94.trailing-spaces
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shengchen.vscode-leetcode
code --install-extension silvenon.mdx
code --install-extension stackery.stackery
code --install-extension teabyii.ayu
code --install-extension tinkertrain.theme-panda
code --install-extension xyc.vscode-mdx-preview
code --install-extension zamerick.black-ocean
code --install-extension zokugun.explicit-folding
