#!/usr/bin/env zsh

# `shell_env.sh` is a main file for any general-case utils.
#
# This file is used as a source file for zsh.

# === Shell parts ===

source "$HOME/.aws/functions"

source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.env_config"
source "$HOME/.shell/.functions"
source "$HOME/.shell/.prompt"
source "$HOME/.shell/golang.zsh"
source "$HOME/.shell/android.zsh"
source "$HOME/.shell/git.zsh"

source "$HOME/.aws/functions"

# === Local variables and overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi
