
#!/bin/zsh

# Show OS info when opening a new terminal
neofetch

plugins=(
	git
	npm
	colored-man-pages
	github
	osx
	heroku
)

export ZSH="$HOME/.oh-my-zsh"
source "$ZSH/oh-my-zsh.sh"
source "$HOME/.shell_env"

# `compinit` scans $fpath, so do this before calling it.
fpath=(~/.zsh/functions $fpath)
autoload -Uz compinit && compinit

ZSH_THEME="powerlevel9k/powerlevel9k"

HYPHEN_INSENSITIVE="true"

DISABLE_AUTO_UPDATE="true"

ENABLE_CORRECTION="true"
