
# Show OS info when opening a new terminal
neofetch

plugins=(
	git
	npm
	nvm
	colored-man-pages
	github
	osx
	heroku
)

export ZSH="$HOME/.oh-my-zsh"
source "$ZSH/oh-my-zsh.sh"
source "$HOME/.shell_env"

ZSH_THEME="powerlevel9k/powerlevel9k"

HYPHEN_INSENSITIVE="true"

DISABLE_AUTO_UPDATE="true"

ENABLE_CORRECTION="true"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/caiokf/development/indebted/finance/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/caiokf/development/indebted/finance/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/caiokf/development/indebted/finance/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/caiokf/development/indebted/finance/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/caiokf/development/indebted/finance/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/caiokf/development/indebted/finance/node_modules/tabtab/.completions/slss.zsh
